# CMake generated Testfile for 
# Source directory: /home/di0/STIR/src/test
# Build directory: /home/di0/STIR/src/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_ROIs "/home/di0/STIR/src/test/test_ROIs")
set_tests_properties(test_ROIs PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;98;create_stir_test;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;0;;/home/di0/STIR/src/test/CMakeLists.txt;89;include;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_warp_image "/home/di0/STIR/src/test/test_warp_image")
set_tests_properties(test_warp_image PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;98;create_stir_test;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;0;;/home/di0/STIR/src/test/CMakeLists.txt;89;include;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_DynamicDiscretisedDensity "/home/di0/STIR/src/test/test_DynamicDiscretisedDensity")
set_tests_properties(test_DynamicDiscretisedDensity PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;98;create_stir_test;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;0;;/home/di0/STIR/src/test/CMakeLists.txt;89;include;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_ScatterSimulation "/home/di0/STIR/src/test/test_ScatterSimulation")
set_tests_properties(test_ScatterSimulation PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;98;create_stir_test;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;0;;/home/di0/STIR/src/test/CMakeLists.txt;89;include;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_ML_norm "/home/di0/STIR/src/test/test_ML_norm")
set_tests_properties(test_ML_norm PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;98;create_stir_test;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;0;;/home/di0/STIR/src/test/CMakeLists.txt;89;include;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_proj_data_info_subsets_pet "/home/di0/STIR/src/test/test_proj_data_info_subsets_pet")
set_tests_properties(test_proj_data_info_subsets_pet PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;98;create_stir_test;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;0;;/home/di0/STIR/src/test/CMakeLists.txt;89;include;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_DateTime "/home/di0/STIR/src/test/test_DateTime")
set_tests_properties(test_DateTime PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;103;create_stir_test;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;0;;/home/di0/STIR/src/test/CMakeLists.txt;89;include;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_radionuclide "/home/di0/STIR/src/test/test_radionuclide")
set_tests_properties(test_radionuclide PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;103;create_stir_test;/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;0;;/home/di0/STIR/src/test/CMakeLists.txt;89;include;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_Array "/home/di0/STIR/src/test/test_Array")
set_tests_properties(test_Array PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_VectorWithOffset "/home/di0/STIR/src/test/test_VectorWithOffset")
set_tests_properties(test_VectorWithOffset PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_ArrayFilter "/home/di0/STIR/src/test/test_ArrayFilter")
set_tests_properties(test_ArrayFilter PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_SeparableMetzArrayFilter "/home/di0/STIR/src/test/test_SeparableMetzArrayFilter")
set_tests_properties(test_SeparableMetzArrayFilter PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_SeparableGaussianArrayFilter "/home/di0/STIR/src/test/test_SeparableGaussianArrayFilter")
set_tests_properties(test_SeparableGaussianArrayFilter PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_NestedIterator "/home/di0/STIR/src/test/test_NestedIterator")
set_tests_properties(test_NestedIterator PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_convert_array "/home/di0/STIR/src/test/test_convert_array")
set_tests_properties(test_convert_array PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IndexRange "/home/di0/STIR/src/test/test_IndexRange")
set_tests_properties(test_IndexRange PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_coordinates "/home/di0/STIR/src/test/test_coordinates")
set_tests_properties(test_coordinates PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_filename_functions "/home/di0/STIR/src/test/test_filename_functions")
set_tests_properties(test_filename_functions PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_KeyParser "/home/di0/STIR/src/test/test_KeyParser")
set_tests_properties(test_KeyParser PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_VoxelsOnCartesianGrid "/home/di0/STIR/src/test/test_VoxelsOnCartesianGrid")
set_tests_properties(test_VoxelsOnCartesianGrid PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_zoom_image "/home/di0/STIR/src/test/test_zoom_image")
set_tests_properties(test_zoom_image PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_ByteOrder "/home/di0/STIR/src/test/test_ByteOrder")
set_tests_properties(test_ByteOrder PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_ImagingModality "/home/di0/STIR/src/test/test_ImagingModality")
set_tests_properties(test_ImagingModality PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_Scanner "/home/di0/STIR/src/test/test_Scanner")
set_tests_properties(test_Scanner PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_ArcCorrection "/home/di0/STIR/src/test/test_ArcCorrection")
set_tests_properties(test_ArcCorrection PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_find_fwhm_in_image "/home/di0/STIR/src/test/test_find_fwhm_in_image")
set_tests_properties(test_find_fwhm_in_image PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_DetectionPosition "/home/di0/STIR/src/test/test_DetectionPosition")
set_tests_properties(test_DetectionPosition PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_proj_data_info "/home/di0/STIR/src/test/test_proj_data_info")
set_tests_properties(test_proj_data_info PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_DetectorCoordinateMap "/home/di0/STIR/src/test/test_DetectorCoordinateMap")
set_tests_properties(test_DetectorCoordinateMap PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_proj_data "/home/di0/STIR/src/test/test_proj_data")
set_tests_properties(test_proj_data PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_proj_data_maths "/home/di0/STIR/src/test/test_proj_data_maths")
set_tests_properties(test_proj_data_maths PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_export_array "/home/di0/STIR/src/test/test_export_array")
set_tests_properties(test_export_array PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_GeneralisedPoissonNoiseGenerator "/home/di0/STIR/src/test/test_GeneralisedPoissonNoiseGenerator")
set_tests_properties(test_GeneralisedPoissonNoiseGenerator PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_multiple_proj_data "/home/di0/STIR/src/test/test_multiple_proj_data")
set_tests_properties(test_multiple_proj_data PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_interpolate_projdata "/home/di0/STIR/src/test/test_interpolate_projdata")
set_tests_properties(test_interpolate_projdata PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_PETSIRDInfo_helpers "/home/di0/STIR/src/test/test_PETSIRDInfo_helpers")
set_tests_properties(test_PETSIRDInfo_helpers PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/cmake/stir_test_exe_targets.cmake;76;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;100;create_stir_test;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_proj_data_info_subsets_spect "/home/di0/STIR/src/test/test_proj_data_info_subsets_spect" "/home/di0/STIR/examples/samples/SPECT_Interfile_header.hs")
set_tests_properties(test_proj_data_info_subsets_spect PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/home/di0/STIR/src/config" _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;110;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_linear_regression "/home/di0/STIR/src/test/test_linear_regression" "/home/di0/STIR/src/test/input/test_linear_regression.in")
set_tests_properties(test_linear_regression PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;114;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_stir_math "/home/di0/STIR/src/test/test_stir_math" "/home/di0/STIR/src/utilities/stir_math")
set_tests_properties(test_stir_math PROPERTIES  DEPENDS "stir_math" _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;122;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_time_of_flight "/home/di0/STIR/src/test/test_time_of_flight")
set_tests_properties(test_time_of_flight PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;127;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IO_ITKMulticomponent "/home/di0/STIR/src/test/test_IO_ITKMulticomponent" "/home/di0/STIR/examples/nifti/disp_4D.nii.gz")
set_tests_properties(test_IO_ITKMulticomponent PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;155;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IO_DiscretisedDensity_test_InterfileOutputFileFormat.in "/home/di0/STIR/src/test/test_IO_DiscretisedDensity" "/home/di0/STIR/src/test/input/test_InterfileOutputFileFormat.in")
set_tests_properties(test_IO_DiscretisedDensity_test_InterfileOutputFileFormat.in PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;162;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IO_DiscretisedDensity_test_InterfileOutputFileFormat_short.in "/home/di0/STIR/src/test/test_IO_DiscretisedDensity" "/home/di0/STIR/src/test/input/test_InterfileOutputFileFormat_short.in")
set_tests_properties(test_IO_DiscretisedDensity_test_InterfileOutputFileFormat_short.in PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;162;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IO_DiscretisedDensity_test_ITKDefaultOutputFileFormat.in "/home/di0/STIR/src/test/test_IO_DiscretisedDensity" "/home/di0/STIR/src/test/input/test_ITKDefaultOutputFileFormat.in")
set_tests_properties(test_IO_DiscretisedDensity_test_ITKDefaultOutputFileFormat.in PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;162;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IO_DiscretisedDensity_test_ITKNiftiOutputFileFormat.in "/home/di0/STIR/src/test/test_IO_DiscretisedDensity" "/home/di0/STIR/src/test/input/test_ITKNiftiOutputFileFormat.in")
set_tests_properties(test_IO_DiscretisedDensity_test_ITKNiftiOutputFileFormat.in PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;162;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IO_ParametricDiscretisedDensity_Interfile "/home/di0/STIR/src/test/test_IO_ParametricDiscretisedDensity" "/home/di0/STIR/src/test/input/test_InterfileOutputFileFormat.in")
set_tests_properties(test_IO_ParametricDiscretisedDensity_Interfile PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;167;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IO_ParametricDiscretisedDensity_Interfile_short "/home/di0/STIR/src/test/test_IO_ParametricDiscretisedDensity" "/home/di0/STIR/src/test/input/test_InterfileOutputFileFormat_short.in")
set_tests_properties(test_IO_ParametricDiscretisedDensity_Interfile_short PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;169;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IO_ParametricDiscretisedDensity_Multi "/home/di0/STIR/src/test/test_IO_ParametricDiscretisedDensity" "/home/di0/STIR/src/test/input/test_MultiOutputFileFormat.in")
set_tests_properties(test_IO_ParametricDiscretisedDensity_Multi PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;171;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IO_DynamicDiscretisedDensity_Interfile "/home/di0/STIR/src/test/test_IO_DynamicDiscretisedDensity" "/home/di0/STIR/src/test/input/test_InterfileOutputFileFormat.in")
set_tests_properties(test_IO_DynamicDiscretisedDensity_Interfile PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;175;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IO_DynamicDiscretisedDensity_Interfile_short "/home/di0/STIR/src/test/test_IO_DynamicDiscretisedDensity" "/home/di0/STIR/src/test/input/test_InterfileOutputFileFormat_short.in")
set_tests_properties(test_IO_DynamicDiscretisedDensity_Interfile_short PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;177;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
add_test(test_IO_DynamicDiscretisedDensity_Multi "/home/di0/STIR/src/test/test_IO_DynamicDiscretisedDensity" "/home/di0/STIR/src/test/input/test_MultiOutputFileFormat.in")
set_tests_properties(test_IO_DynamicDiscretisedDensity_Multi PROPERTIES  _BACKTRACE_TRIPLES "/home/di0/STIR/src/test/CMakeLists.txt;179;ADD_TEST;/home/di0/STIR/src/test/CMakeLists.txt;0;")
